### PR TITLE
Support 4.2.10

### PR DESCRIPTION
**Pull request by Eric-Guo**
Maybe better than #14 implement? @redtachyons @bf4

### CODE REVIEW

**Comment by josephpage** [comment]
```
if Gem::Version.new(ActiveRecord::VERSION::STRING) < Gem::Version.new('4.2.3')
  warn 'Patching ActiveRecord::Relation#or. This might blow up'
end 
```
Maybe ?
Inspiration from : https://medium.com/@edgar/how-to-compare-semantic-version-strings-in-ruby-95fbf067de32

**Comment by redtachyons** [comment]
@josephpage `Gem::Version.new(ActiveRecord::VERSION::STRING)` is same as `ActiveRecord.version`, right ?

**Comment by josephpage** [comment]
Exact :)  my bad
https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/gem_version.rb#L3

**Comment by redtachyons** [comment]
@josephpage Well, that is what I did in #14 :-)

**Comment by josephpage** [comment]
Yes...
Really sorry, I don't understand the debate...

**Comment by bf4** [comment]
@Eric-Guo I don't think any changes are needed except to perhaps remove that line. It's intent when I wrote it was that I extracted the code without tests, so only using it on different Rails versions was sufficient to consider it working and not broken.

Perhaps the goal can be to change the warning to 

> You are using where-or on Rails 4.2.9 which has not yet been confirmed as compatible. Please create and issue at https://github.com/Eric-Guo/where-or/issue with your experience

and to appear in Rails version > 4.2.3 and < 4.2.6 or something

The < 4.2.3 warning means I have no idea if it the patch will work on Rails 4.2.1, 4.1. or whatever

**Comment by josephpage** [comment]
Thanks.
I have used it without issues in production with 4.2.6, 4.2.7 and 4.2.8.
Seems to work fine with 4.2.10 (a bit early to be sure).

**Pull request merged**
